{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: user{{ $attendee }}-peachpal
  labels:
    kubernetes.io/metadata.name: user{{ $attendee }}-peachpal
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/description: 'user{{ $attendee }} Peachpal Development Environment'
    openshift.io/display-name: 'user{{ $attendee }}-peachpal'
    openshift.io/requester: 'user{{ $attendee }}'
spec:
  finalizers:
    - kubernetes
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user{{ $attendee }}-peachpal-admin
  namespace: user{{ $attendee }}-peachpal
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user{{ $attendee }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
{{- end}}